export const DEFECT_TYPES = [
  { code: "H01", name: "ลับบาง-หนา (R)" },
  { code: "H02", name: "ลับบาง-บาง (R)" },
  { code: "H03", name: "ลับบาง-บาง" },
  { code: "H04", name: "ลับบางเล็ก" },
  { code: "H05", name: "ลับบาง-ใหญ่" },
  { code: "H06", name: "ลับบางซ้อน" },
  { code: "H07", name: "ลับบาง 2 ข้างไม่เท่ากัน" },
  { code: "H08", name: "ลับบางเป็นคลื่น" },
  { code: "H09", name: "ลับบางลาย" },
  { code: "H10", name: "ลับบางไหม้" },
  { code: "H11", name: "ใบมีดงอ" },
  { code: "H12", name: "ลองหิน" },
  { code: "H13", name: "ลับบางเอียง" },
  { code: "H14", name: "ลับบางหยาบ" },
  { code: "H15", name: "อื่นๆ" },
] as const;